### ISSUE TITLE
piskel? 

### ISSUE THREAD

**Issue by blurymind** [Technohacker/godot_pixelorama_importer#1]
Looking at
https://github.com/Technohacker/godot_pixelorama_importer/blob/master/addons/godot_pixelorama_importer/pixelorama_importer.gd#L31

Does this suggest that the extension imports piskel files?
https://www.piskelapp.com/

**Comment by Technohacker** [comment]
Oops my bad, forgot to replace it there :joy: 
This addon was built with the same structure as [my Piskel plugin](https://github.com/Technohacker/godot_piskel_importer), hence the similarities :D

**Comment by blurymind** [comment]
nice, I didnt see that there is also a piskel one. Thank you for developing these - they are a good example to study for other file types I suppose
